# Generated by Django 6.0.3 on 2026-03-13 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YogaClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('short_description', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('instructor_name', models.CharField(max_length=120)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('focus', models.CharField(blank=True, max_length=120)),
                ('cover_image', models.ImageField(blank=True, upload_to='class-covers/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Yoga classes',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('yoga_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.yogaclass')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('yoga_class', 'client_email'), name='unique_booking_email_per_class')],
            },
        ),
    ]
