# Generated by Django 6.0.3 on 2026-03-15 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_studio_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='studio',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.studio'),
        ),
        migrations.AlterField(
            model_name='client',
            name='studio',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='booking.studio'),
        ),
        migrations.AlterField(
            model_name='smsreminderlog',
            name='studio',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='sms_logs', to='booking.studio'),
        ),
        migrations.AlterField(
            model_name='yogaclass',
            name='studio',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='booking.studio'),
        ),
    ]
